---
title: "CLT_WUP"
author: "Adam Ayala"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"    
    
---

kkardashtemp  see code below

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(lattice)
```

```{r}
Homers_data <- read.csv(file="Homers_data.csv")

my1000 <- sample(Homers_data , size = 1000, replace=T)

```

```{r}

library(ggplot2)
sampleNumber = sample(1:10000, size = 1000)
library(dplyr)
my1000 <- Homers_data[sampleNumber, ]
names(my1000)
# Basic density
p <- ggplot(my1000, aes(x=kkardashtemp,col=sex)) + 
  geom_density()
p
# Add mean line
p+ geom_vline(aes(xintercept=mean(kkardashtemp)),
            color="blue", linetype="dashed", size=1)
print(paste('mean = ', mean(my1000$kkardashtemp),' sd = ',sd(my1000$kkardashtemp)))
```

```{r}
numb=2
Hdata = Homers_data[sample(1:1000, size=numb*1000, replace=T),"kkardashtemp"]
mdata  <-matrix(Hdata,nrow=1000,ncol=numb)
x.avg <- apply(mdata,1,mean)
my1000$k2 = x.avg

p <- ggplot(my1000, aes(x=k2)) + 
  geom_density() 
p

# Add mean line
  geom_vline(aes(xintercept=mean(k2)),
            color="blue", linetype="dashed", size=1)
print(paste('mean = ', mean(my1000$k2),' sd = ',sd(my1000$k2)))

```

 

```{r}
numb=25
Hdata = Homers_data[sample(1:1000, size=numb*1000, replace=T),"kkardashtemp"]
mdata <-matrix(Hdata,nrow=1000,ncol=numb)
x.avg <- apply(mdata,1,mean)
my1000$k25 = x.avg

p <- ggplot(my1000, aes(x=k25), (Col=sex))+
geom_density()

# Add mean line
geom_vline(aes(xintercept=mean(k25)),
color="blue", linetype="dashed", size=1)
p + ggtitle("n = 25") +
xlab("temperature") + ylab("desnity")

print(paste('mean = ', mean(my1000$k25),' sd = ',sd(my1000$k25)))

```

The mean is still close to 50 and the standard deviation has decreased to be approximately 8. A predicted standard deviation using sqrt(25) gives us about 8.276 which is still close for the approximate value of 8. The graph is starting to look more similar on the sides but the tip at around 50 does stand out more often with different data. 